language: java
jdk:
  - oraclejdk7
script: "mvn clean deploy --settings settings.xml"
notifications:
  email: false
env:
  global:
    - secure: "iRkUrGn+D9wjUuqwZar3J5zGjaXFbu67tVoPC94qzs7OrjgqR9mLgpDK/eDfAGe0R5Irt7dgLuSkIFmbfsn1Honxc1Bt88/kA8ZLJUhJG7PHoX2wYlmNIcCKWM1BXGyD9G6u1cg0MluqVd3xvXBwWp/8pw3vWEgvGj7T8g4KMI8="
    - secure: "L+j2UJZCu2/W1w1vpVdF6ivW/aML+xQ6V2w0rRT8juMpDOmfXtpDHW3LQQG3szRSH+Lt5dFN2ZANkV0RYdzh1ZAP88HuDmdWVANlTxoxiBByfZk3kPBK2gbLFwWo1hwBGfCqj1vpwbTm+xzaxiXqvK/+fCRSH3enBYCGinFIvmM="

