#     _____                  _            _     _____                               _____             __ _       
#    / ____|                (_)          | |   / ____|                             / ____|           / _(_)      
#   | (___  _   _ _ ____   _____   ____ _| |  | |  __  __ _ _ __ ___   ___  ___   | |     ___  _ __ | |_ _  __ _ 
#    \___ \| | | | '__\ \ / / \ \ / / _` | |  | | |_ |/ _` | '_ ` _ \ / _ \/ __|  | |    / _ \| '_ \|  _| |/ _` |
#    ____) | |_| | |   \ V /| |\ V / (_| | |  | |__| | (_| | | | | | |  __/\__ \  | |___| (_) | | | | | | | (_| |
#   |_____/ \__,_|_|    \_/ |_| \_/ \__,_|_|   \_____|\__,_|_| |_| |_|\___||___/   \_____\___/|_| |_|_| |_|\__, |
#                                                                                                           __/ |
#                                                                                                          |___/ 
# This is a community project, join in http://dev.bukkit.org/bukkit-plugins/the-survival-games/.

#Bungeecord Mode
bungeecord-mode: false

#SETTINGS IF BUNGEECORD MODE IS TRUE

#Define if the server should be a hub
hub-server: false

#END THOSE SETTINGS

#Starting points per player:
starting-points: 100

#Allow Double-Jump in game
allow-double-jump-IG: false

#Allow Double-Jump in lobby
allow-double-jump: true

#Arenas Config
#Specify each arena's .yml file here
arenas:
  - testArena.yml
  - testArena2.yml

#Welcome Message
welcome-message:
  - '&eHi there, and welcome to'
  - '&a&lThe Survival Games Server'
  - '&2Read the book in your inventory for more information'
#Signs config
signs:
  #placeholders:
  #%numpl% = online players
  #%maxpl% = max players
  #%motd% = motd
  #%displayname% = displayname
  #%isonline% whether the server is online or offline
  
  #"inventory" is a reserved layout name! Don't use it
  layouts:
    #you can change the default layout but don't delete it!
    default:
      teleport: true
      layout:
        - '&bTeleport to:'
        - '%motd%'
        - '&f&l%numpl%/%maxpl%'
        - '%isonline%'
      join: '&a[Join]'
      cantJoin: '&c[NotJoinable]'
      offline-int: '-'
breaks-allowed:
  - 'LEAVES'
  - 'LEAVES_2'
  - 'BROWN_MUSHROOM'
  - 'RED_MUSHROOM'
  - 'VINE'
  - 'GRASS'
